[package]
description = "A cli tool for working with different types of databases"
edition = "2021"
name = "ginger-db"
version = "0.10.0-nightly.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
MetadataService = {path = "./MetadataService_client"}
clap = {version = "4.5.7", features = ["derive"]}
crossterm = "0.28.1"
dirs = "5.0.1"
ginger-shared-rs = {version = "0.45.0-nightly.0", organization = "ginger-society"}
inquire = {version = "0.6.2", features = ["date"]}
ratatui = "0.28.1"
schema-gen-service = {path = "./schema-gen-service_client"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tera = "1.20.0"
tokio = {version = "1", features = ["full"]}
toml = "0.8.14"
tokio-tungstenite = { version = "0.26.2", features = ["tokio-native-tls", "native-tls"] }
futures-util = "0.3.31"
IAMService = { path = "./IAMService_client" }


[package.metadata]
organization = "ginger-society"
