lang = "Rust"
organization_id = "ginger-society"
dir = "."

[services."@ginger-society/MetadataService"]
prod = "https://api.gingersociety.org/metadata"
stage = "https://api-staging.gingersociety.org/metadata"

[services."@ginger-society/schema-gen-service"]
stage = "https://db-compose-runtime-test-env-675766508318.asia-south1.run.app"
prod = "https://db-compose-test-env.gingersociety.org/"

[portals_refs]

[ws_refs."@ginger-society/MetadataService"]
stage = ""
prod = ""

[ws_refs."@ginger-society/schema-gen-service"]
stage = ""
prod = ""

[urls]
