# Generated by Ginger 5.3.4 on 2024-06-10 16:09

from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_student_has_cab_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='has_cab_service',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
